version: "3.8"

services:
  demo-db:
    container_name: demo-db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: demo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres